---
  - hosts: instance
    vars_files:
      - deployment_vars.yml
    become: true
    tasks:
      - name: Run drone server docker command
        shell: docker run --volume=/var/lib/drone:/data --env=DRONE_GITHUB_CLIENT_ID={{ drone_github_client_id }} --env=DRONE_GITHUB_CLIENT_SECRET="f42b9548f81e2e4a294c3dad8e4f31fbbafe548e" --env=DRONE_RPC_SECRET="d567696b30af22da94a58a234df2119d" --env=DRONE_TLS_AUTOCERT=true --env=DRONE_SERVER_HOST="drone.clouddesigndev.com" --env=DRONE_SERVER_PROTO=https --env=DRONE_USER_CREATE=username:greyhoundforty,admin:true --env=DRONE_USER_FILTER=greyhoundforty,cloud-design-dev  --publish=80:80 --publish=443:443 --restart=always --detach=true --name=drone drone/drone:1
      - name: Run drone runner docker command
        shell: docker run -d -v /var/run/docker.sock:/var/run/docker.sock -e DRONE_RPC_PROTO=https -e DRONE_RPC_HOST="drone.clouddesigndev.com" -e DRONE_RPC_SECRET="d567696b30af22da94a58a234df2119d" -e DRONE_RUNNER_CAPACITY=5 -p 3000:3000 --restart always --name runner   drone/drone-runner-docker:1
