---
  - hosts: drone
    become: true
    vars:
      certbot_admin_email: ryantiffany@fastmail.com
      certbot_create_if_missing: true
      certbot_create_standalone_stop_services: []
      certbot_certs:
        - domains: ["drone.clouddesigndev.com"]
    roles: 
      - role: geerlingguy.certbot